version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app

  proxy:
    build: docker/nginx/.
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf'
      - './static:/static'
    ports:
      - '8000:80'
    depends_on:
      - web
